version: 2

project_name: inject

before:
  hooks:
    - go mod tidy

builds:
  - id: inject
    binary: inject
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w

archives:
  - id: default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

brews:
  - name: inject
    homepage: "https://github.com/dynamicHarsh/env-pull"
    description: "Universal Secrets Adapter"
    license: "MIT"
    repository:
      owner: dynamicHarsh
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    directory: Formula
    install: |
      bin.install "inject"
      bin.install_symlink "inject" => "env-pull"
    test: |
      system "#{bin}/inject", "--help"

scoops:
  - name: inject
    homepage: "https://github.com/dynamicHarsh/env-pull"
    description: "Universal Secrets Adapter"
    license: "MIT"
    repository:
      owner: dynamicHarsh
      name: scoop-bucket
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    directory: bucket

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - "Merge pull request"
      - "Merge remote-tracking branch"
      
